import Footer from "@/components/Footer";
import Header from "@/components/Header";

import type { Metadata } from "next";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Cicero",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = cookies().get("user")?.value;
  return (
    <div className="h-screen overflow-x-hidden scroll-smooth">
      <Header userId={user ? user : ""} />
      <main>{children}</main>
      <Footer />
    </div>
  );
}
