
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import MobileNav from "@/components/Nav/MobileNav";
import {Navbar} from "@/components/Nav/Navbar";


import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function MainLayout({
	children,
}: {
	children: React.ReactNode;
}) {

	return (
		<div className="h-screen overflow-x-hidden scroll-smooth">
			<Header />
			<main>{children}</main>
			<Footer />
		</div>
	);
}